"""Canonical Remediation Contracts for SentinelFlow Phase P07.

The RemediationAgent (Autonomy Level A2: Sandbox Candidate Creation) proposes
allowlisted, structured remediation intents. Authoritative candidate bytes and
numerical totals are strictly computed and generated by the Go Control Plane.
"""

from enum import Enum
from typing import List, Literal, Optional
from pydantic import BaseModel, Field


class RemediationOperationType(str, Enum):
    """Allowlisted deterministic repair operation types for P07."""
    RECOMPUTE_BATCH_CONTROL_TOTAL = "RECOMPUTE_BATCH_CONTROL_TOTAL"
    RECOMPUTE_FILE_CONTROL_TOTAL = "RECOMPUTE_FILE_CONTROL_TOTAL"


class RemediationOperation(BaseModel):
    """Typed repair intent targeting a semantic structure in the NACHA file."""
    operation_type: RemediationOperationType = Field(
        ..., description="Allowlisted operation enum"
    )
    target_ref: str = Field(
        ..., description="Semantic target reference e.g. 'BATCH-1' or 'FILE_CONTROL'"
    )
    finding_refs: List[str] = Field(
        default_factory=list, description="Validation finding IDs addressed by this operation"
    )
    rationale: str = Field(
        ..., description="Technical explanation of why this deterministic operation resolves the findings"
    )
    evidence_refs: List[str] = Field(
        default_factory=list, description="Authorized evidence IDs cited for this operation"
    )


class RemediationPlan(BaseModel):
    """Structured remediation proposal generated by RemediationAgent."""
    schema_version: Literal["1.0"] = "1.0"
    workflow_id: str = Field(..., description="Authoritative workflow identifier")
    tenant_id: str = Field(..., description="Authoritative tenant identifier")
    incident_id: int = Field(..., description="Quarantined incident ID")
    artifact_id: int = Field(..., description="Quarantined parent artifact ID")
    expected_parent_sha256: str = Field(..., description="SHA-256 hash of the parent artifact")
    attempt_number: int = Field(1, ge=1, le=3, description="Candidate attempt number (1-3)")
    plan_hash: Optional[str] = Field(None, description="Deterministic hash of the plan")
    operations: List[RemediationOperation] = Field(
        ..., min_length=1, description="List of allowlisted remediation operations"
    )
    finding_refs: List[str] = Field(
        default_factory=list, description="All validation findings addressed by this plan"
    )
    unresolved_findings: List[str] = Field(
        default_factory=list, description="Findings that cannot be deterministically repaired"
    )
    confidence: Literal["HIGH", "MEDIUM", "LOW"] = Field(
        "HIGH", description="Agent confidence assessment in the proposed repair"
    )
    requires_human_attention: bool = Field(
        False, description="Flag indicating if unusual patterns warrant human review"
    )
    evidence_refs: List[str] = Field(
        default_factory=list, description="All authorized evidence citations supporting the plan"
    )
    statement: str = Field(
        "The RemediationAgent proposes typed remediation intent. Authoritative values and candidate artifact generation are strictly computed and executed by the Go Control Plane.",
        description="Formal non-authority declaration statement"
    )
