server {
    listen 8080;
    listen 3000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/v1/ {
        proxy_pass https://sentinelflow-gateway-axrdwvptka-uc.a.run.app/api/v1/;
        proxy_set_header Host sentinelflow-gateway-axrdwvptka-uc.a.run.app;
        proxy_ssl_server_name on;
    }
}

