// Package objectstore holds financial artifacts as immutable objects.
//
// The contract invariant it exists to serve is that the original artifact is
// immutable and repair creates a new derived artifact. Before this package,
// `storage_path` was the string "/s3/incoming/" concatenated with the client's
// filename, no object was ever written anywhere, and the whole file body was
// held in memory and persisted into a database column.
//
// Three properties are structural here rather than conventional:
//
//   - Object keys are generated by the server from random bytes. A client
//     filename never contributes to a key, so no filename -- including
//     "../../etc/passwd" or one with a NUL byte -- can influence where an object
//     lands. Path traversal is not filtered; it is unrepresentable.
//   - Writes are streaming and bounded. The hash, the byte count and the media
//     sniff are computed as bytes pass through, so a large artifact never
//     becomes a large allocation.
//   - A completed object is never overwritten. A failed or interrupted write
//     leaves no object at all, rather than a truncated one that would parse as
//     a shorter valid file.
package objectstore

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/http"
	"path"
	"strings"
	"time"
	"unicode"
)

var (
	// ErrObjectExists means a key already holds an object. It is always a
	// programming error or an attempted overwrite; there is no recovery that
	// involves replacing the stored bytes.
	ErrObjectExists = errors.New("object already exists and is immutable")

	// ErrObjectNotFound distinguishes absent from forbidden nowhere: callers
	// reach this package only through a tenant-scoped key.
	ErrObjectNotFound = errors.New("object not found")

	// ErrTooLarge means the stream exceeded the caller's byte limit. No object
	// is left behind.
	ErrTooLarge = errors.New("artifact exceeds the maximum permitted size")

	// ErrEmpty means the stream carried no bytes. An empty artifact is refused
	// at the storage boundary as well as at validation, because storing one
	// creates a record that something arrived when nothing did.
	ErrEmpty = errors.New("artifact is empty")

	// ErrSizeMismatch means the declared length and the received length differ.
	ErrSizeMismatch = errors.New("received byte count does not match the declared length")
)

// ObjectInfo is the metadata of a stored object.
type ObjectInfo struct {
	Key       string
	SizeBytes int64
	SHA256    string
	StoredAt  time.Time
}

// PutResult describes what was actually written, measured during the write
// rather than declared by the caller.
type PutResult struct {
	Key       string
	SizeBytes int64
	SHA256    string

	// MediaType is sniffed from the leading bytes. It is advisory: a NACHA file
	// is plain text and sniffing cannot confirm a financial format. It exists
	// to catch the obvious case of a caller uploading an archive or an
	// executable to a text-only ingress.
	MediaType string
}

// ObjectStore is the storage boundary.
//
// Every adapter must satisfy the following, and the shared conformance suite in
// conformance_test.go checks each point against every implementation:
//
//   - Put streams. It must not require the payload to fit in memory, and must
//     not read the whole payload before starting to write.
//   - Put computes the SHA-256 and byte count from the bytes it actually
//     received, never from a caller-declared value.
//   - Put refuses a key that already holds an object, with ErrObjectExists.
//   - Put leaves no object when it fails for any reason -- limit exceeded,
//     reader error, empty stream, or a cancelled context. A partial financial
//     artifact must not exist, because a truncated file often parses.
//   - Get returns ErrObjectNotFound for an absent key.
//   - No method accepts a caller-supplied path. Keys come from NewKey.
type ObjectStore interface {
	// Put writes at most limit bytes from r to key.
	Put(ctx context.Context, key string, r io.Reader, limit int64) (PutResult, error)

	// Get opens a stored object for streaming.
	Get(ctx context.Context, key string) (io.ReadCloser, error)

	// Stat returns metadata without transferring the object.
	Stat(ctx context.Context, key string) (ObjectInfo, error)
}

// NewKey generates an object key.
//
// The key is entirely server-side: a tenant prefix, a date prefix for
// operational partitioning, and 128 bits from crypto/rand. No part of it comes
// from the caller, which is what makes path traversal and key collision
// impossible rather than merely filtered.
//
// The date prefix is derived from the ingest time in UTC. It is for lifecycle
// policy and for making a bucket listing navigable; nothing reads business
// meaning out of it.
func NewKey(tenantID string, now time.Time) (string, error) {
	if tenantID == "" {
		return "", errors.New("an object key requires a tenant")
	}
	if strings.ContainsAny(tenantID, "/\\.") {
		// A tenant id is an internal identifier from a verified claim, but it
		// reaches a path here, so it is checked rather than trusted.
		return "", fmt.Errorf("tenant id %q is not usable in an object key", tenantID)
	}
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("generate object key: %w", err)
	}
	return path.Join(
		"tenant", tenantID,
		now.UTC().Format("2006/01/02"),
		hex.EncodeToString(buf),
	), nil
}

// DerivedKey generates a key for an artifact derived from another.
//
// It is a fresh random key, not a modification of the source key. Deriving
// "source-key.repaired" would make the relationship a string convention that
// something would eventually parse, and would put the derived object one
// character away from overwriting its source.
func DerivedKey(tenantID string, now time.Time) (string, error) {
	return NewKey(tenantID, now)
}

// maxFilenameLength bounds the stored display name. It is not a filesystem
// limit -- the name never becomes a path -- but an unbounded string from a
// client ends up in logs, in a UI and in an export.
const maxFilenameLength = 255

// NormalizeFilename produces a safe display name for a client-supplied
// filename.
//
// This is defence in depth and nothing more. The filename does not determine
// where anything is stored, so a hostile name cannot escape a directory. What
// it can do is inject control characters into a log line, break a UI, or carry
// a path that a future maintainer decides to "helpfully" use as a key. This
// function removes that material at the boundary.
//
// It returns the cleaned name and whether anything was changed, so the caller
// can record that the client's name was not what was stored.
func NormalizeFilename(raw string) (string, bool) {
	original := raw

	// Both separators, because a Windows client sends backslashes and
	// path.Base would treat the whole thing as one component.
	raw = strings.ReplaceAll(raw, "\\", "/")
	raw = path.Base(path.Clean("/" + raw))

	// path.Clean("/..") is "/", whose Base is "/".
	if raw == "/" || raw == "." || raw == ".." {
		raw = ""
	}

	// Strip anything non-printable, which covers NUL bytes, newlines that would
	// forge a log record, and terminal escape sequences.
	raw = strings.Map(func(r rune) rune {
		if r == unicode.ReplacementChar || !unicode.IsPrint(r) {
			return -1
		}
		return r
	}, raw)

	raw = strings.TrimSpace(raw)
	// A leading dot makes a hidden file and is never meaningful for an
	// artifact name.
	raw = strings.TrimLeft(raw, ".")

	if len(raw) > maxFilenameLength {
		raw = raw[:maxFilenameLength]
	}
	if raw == "" {
		raw = "unnamed-artifact"
	}
	return raw, raw != original
}

// mediaSniffBytes is what http.DetectContentType inspects.
const mediaSniffBytes = 512

// hashingWriter measures a stream as it passes: SHA-256, byte count, and the
// leading bytes for a media sniff.
//
// Measuring during the write is the point. A hash computed by re-reading what
// was stored would prove the storage round-tripped, not that the bytes received
// are the bytes stored, and would require a second pass over the whole object.
type hashingWriter struct {
	hasher  interface{ Write([]byte) (int, error) }
	written int64
	head    []byte
}

func newHashingWriter() *hashingWriter {
	return &hashingWriter{hasher: sha256.New(), head: make([]byte, 0, mediaSniffBytes)}
}

func (h *hashingWriter) Write(p []byte) (int, error) {
	if _, err := h.hasher.Write(p); err != nil {
		return 0, err
	}
	if len(h.head) < mediaSniffBytes {
		room := mediaSniffBytes - len(h.head)
		if room > len(p) {
			room = len(p)
		}
		h.head = append(h.head, p[:room]...)
	}
	h.written += int64(len(p))
	return len(p), nil
}

func (h *hashingWriter) sum() string {
	type sumer interface{ Sum([]byte) []byte }
	return hex.EncodeToString(h.hasher.(sumer).Sum(nil))
}

func (h *hashingWriter) mediaType() string {
	if len(h.head) == 0 {
		return ""
	}
	return http.DetectContentType(h.head)
}

// boundedReader enforces the byte limit during the copy rather than after it.
//
// io.LimitReader alone would silently truncate at the limit, and a truncated
// NACHA file parses -- it simply describes fewer payments. The distinction
// between "the file was this long" and "the file was longer and we stopped
// reading" has to be preserved, so this reads one byte past the limit and
// reports ErrTooLarge rather than returning a short, plausible file.
type boundedReader struct {
	r         io.Reader
	remaining int64
	exceeded  bool
}

func (b *boundedReader) Read(p []byte) (int, error) {
	if b.remaining <= 0 {
		// Try one more byte. If it is there, the source was over the limit.
		var probe [1]byte
		n, _ := b.r.Read(probe[:])
		if n > 0 {
			b.exceeded = true
			return 0, ErrTooLarge
		}
		return 0, io.EOF
	}
	if int64(len(p)) > b.remaining {
		p = p[:b.remaining]
	}
	n, err := b.r.Read(p)
	b.remaining -= int64(n)
	return n, err
}
