package returnrisk

import (
	"fmt"
	"strings"
)

// TaxonomyVersion defines the active representative ACH return-code schema version.
const TaxonomyVersion = "ACH-RETURN-TAXONOMY-V1.1-P12.5"

const taxonomyRetrievedDate = "2026-08-23"

func publicSources(extra ...PublicSourceProvenance) []PublicSourceProvenance {
	base := []PublicSourceProvenance{
		{
			SourceID:          "NACHA_PUBLIC_ISO20022_RETURN_GUIDE_2023",
			SourceName:        "Nacha ISO 20022 Mapping Guide - Return Reason Codes",
			Reference:         "https://www.nacha.org/system/files/2023-07/ACH-ISO-20022-Mapping-Guide.pdf",
			RetrievedDate:     taxonomyRetrievedDate,
			SemanticsVerified: true,
		},
		{
			SourceID:          "NACHA_PUBLIC_NETWORK_RISK_TOPICS",
			SourceName:        "Nacha ACH Network Risk and Enforcement Topics",
			Reference:         "https://www.nacha.org/rules/ach-network-risk-and-enforcement-topics",
			RetrievedDate:     taxonomyRetrievedDate,
			SemanticsVerified: true,
		},
	}
	return append(base, extra...)
}

var unauthorizedReasonSource = PublicSourceProvenance{
	SourceID:          "NACHA_PUBLIC_UNAUTHORIZED_REASON_DIFFERENTIATION",
	SourceName:        "Nacha Differentiating Unauthorized Return Reasons",
	Reference:         "https://www.nacha.org/news/differentiating-unauthorized-return-reasons",
	RetrievedDate:     taxonomyRetrievedDate,
	SemanticsVerified: true,
}

var r16TransitionSource = PublicSourceProvenance{
	SourceID:          "NACHA_PUBLIC_R90_RULE_2026",
	SourceName:        "Nacha New Return Reason Code R90 for Sanctions Screening",
	Reference:         "https://www.nacha.org/rules/new-return-reason-code-r90-sanctions-screening",
	RetrievedDate:     taxonomyRetrievedDate,
	SemanticsVerified: true,
}

// Catalog holds a representative MVP set of ACH return-code definitions.
// It is deliberately not a complete ACH return-code catalog; for example R51 remains deferred.
var Catalog = map[string]ACHReturnCode{
	"R01": {
		Code:                 "R01",
		ShortLabel:           "INSUFFICIENT_FUNDS",
		Title:                "Insufficient Funds",
		Description:          "Available balance is not sufficient to cover the dollar value of the debit entry.",
		NormalizedCategory:   CategoryInsufficientFunds,
		OperationalSeverity:  SeverityMedium,
		RetryCharacteristic:  RetryableOnce,
		AccountDataIssue:     false,
		AuthorizationIssue:   false,
		AdministrativeIssue:  false,
		ReturnWindow:         ReturnWindow2BankingDays,
		ThresholdCategory:    ThresholdOverall15Percent,
		BaseSeverity:         45.0,
		TaxonomyVersion:      TaxonomyVersion,
		OperationalGuidance:  GuidanceStandardExceptionReview,
		GuidanceSummary:      "Review the return event and any reinitiation eligibility under the institution's current controls; do not infer release authority from risk score.",
		SourceProvenance:     publicSources(),
	},
	"R02": {
		Code:                 "R02",
		ShortLabel:           "ACCOUNT_CLOSED",
		Title:                "Account Closed",
		Description:          "A previously active account has been closed by the customer or RDFI.",
		NormalizedCategory:   CategoryAccountStatus,
		OperationalSeverity:  SeverityHigh,
		RetryCharacteristic:  NonRetryable,
		AccountDataIssue:     true,
		AuthorizationIssue:   false,
		AdministrativeIssue:  true,
		ReturnWindow:         ReturnWindow2BankingDays,
		ThresholdCategory:    ThresholdAdministrative3Percent,
		BaseSeverity:         50.0,
		TaxonomyVersion:      TaxonomyVersion,
		OperationalGuidance:  GuidanceCorrectionRequired,
		GuidanceSummary:      "Review the account status and obtain corrected payment instructions before any subsequent processing decision.",
		SourceProvenance:     publicSources(),
	},
	"R03": {
		Code:                 "R03",
		ShortLabel:           "NO_ACCOUNT_UNABLE_TO_LOCATE",
		Title:                "No Account / Unable to Locate Account",
		Description:          "The account number does not correspond to an account at the RDFI or the account cannot be located.",
		NormalizedCategory:   CategoryAccountData,
		OperationalSeverity:  SeverityHigh,
		RetryCharacteristic:  RetryableWithCorrection,
		AccountDataIssue:     true,
		AuthorizationIssue:   false,
		AdministrativeIssue:  true,
		ReturnWindow:         ReturnWindow2BankingDays,
		ThresholdCategory:    ThresholdAdministrative3Percent,
		BaseSeverity:         55.0,
		TaxonomyVersion:      TaxonomyVersion,
		OperationalGuidance:  GuidanceCorrectionRequired,
		GuidanceSummary:      "Require account-data review and correction before considering a subsequent entry.",
		SourceProvenance:     publicSources(),
	},
	"R04": {
		Code:                 "R04",
		ShortLabel:           "INVALID_ACCOUNT_STRUCTURE",
		Title:                "Invalid Account Number Structure",
		Description:          "The account number structure is invalid for the receiving institution.",
		NormalizedCategory:   CategoryAccountData,
		OperationalSeverity:  SeverityHigh,
		RetryCharacteristic:  RetryableWithCorrection,
		AccountDataIssue:     true,
		AuthorizationIssue:   false,
		AdministrativeIssue:  true,
		ReturnWindow:         ReturnWindow2BankingDays,
		ThresholdCategory:    ThresholdAdministrative3Percent,
		BaseSeverity:         55.0,
		TaxonomyVersion:      TaxonomyVersion,
		OperationalGuidance:  GuidanceCorrectionRequired,
		GuidanceSummary:      "Review and correct the account information before considering a subsequent entry.",
		SourceProvenance:     publicSources(),
	},
	"R05": {
		Code:                 "R05",
		ShortLabel:           "UNAUTHORIZED_CONSUMER_CORPORATE_SEC",
		Title:                "Unauthorized Debit to Consumer Account Using Corporate SEC Code",
		Description:          "A debit using a corporate SEC code was returned as unauthorized from a consumer account.",
		NormalizedCategory:   CategoryUnauthorized,
		OperationalSeverity:  SeverityCritical,
		RetryCharacteristic:  NonRetryable,
		AccountDataIssue:     false,
		AuthorizationIssue:   true,
		AdministrativeIssue:  false,
		ReturnWindow:         ReturnWindow60CalendarDays,
		ThresholdCategory:    ThresholdUnauthorized05Percent,
		BaseSeverity:         90.0,
		TaxonomyVersion:      TaxonomyVersion,
		OperationalGuidance:  GuidanceAuthorizationReviewRequired,
		GuidanceSummary:      "Route for authorization review and do not automatically reinitiate based on the risk assessment.",
		SourceProvenance:     publicSources(unauthorizedReasonSource),
	},
	"R07": {
		Code:                 "R07",
		ShortLabel:           "AUTHORIZATION_REVOKED",
		Title:                "Authorization Revoked by Customer",
		Description:          "The Receiver indicates that authorization for the debit was revoked.",
		NormalizedCategory:   CategoryUnauthorized,
		OperationalSeverity:  SeverityCritical,
		RetryCharacteristic:  NonRetryable,
		AccountDataIssue:     false,
		AuthorizationIssue:   true,
		AdministrativeIssue:  false,
		ReturnWindow:         ReturnWindow60CalendarDays,
		ThresholdCategory:    ThresholdUnauthorized05Percent,
		BaseSeverity:         85.0,
		TaxonomyVersion:      TaxonomyVersion,
		OperationalGuidance:  GuidanceAuthorizationReviewRequired,
		GuidanceSummary:      "Route for authorization review and do not automatically reinitiate based on historical patterns or risk score.",
		SourceProvenance:     publicSources(unauthorizedReasonSource),
	},
	"R08": {
		Code:                 "R08",
		ShortLabel:           "PAYMENT_STOPPED",
		Title:                "Payment Stopped",
		Description:          "The Receiver has placed a stop payment on the debit entry.",
		NormalizedCategory:   CategoryAdministrative,
		OperationalSeverity:  SeverityHigh,
		RetryCharacteristic:  NonRetryable,
		AccountDataIssue:     false,
		AuthorizationIssue:   true,
		AdministrativeIssue:  false,
		ReturnWindow:         ReturnWindow2BankingDays,
		ThresholdCategory:    ThresholdOverall15Percent,
		BaseSeverity:         60.0,
		TaxonomyVersion:      TaxonomyVersion,
		OperationalGuidance:  GuidanceReviewRequired,
		GuidanceSummary:      "Review the stop-payment context before any subsequent processing decision.",
		SourceProvenance:     publicSources(),
	},
	"R10": {
		Code:                 "R10",
		ShortLabel:           "ORIGINATOR_NOT_KNOWN_OR_NOT_AUTHORIZED",
		Title:                "Customer Advises Originator is Not Known to Receiver and/or Originator is Not Authorized by Receiver to Debit Receiver's Account",
		Description:          "The Receiver advises that the Originator is not known to the Receiver and/or is not authorized by the Receiver to debit the Receiver's account.",
		NormalizedCategory:   CategoryUnauthorized,
		OperationalSeverity:  SeverityCritical,
		RetryCharacteristic:  NonRetryable,
		AccountDataIssue:     false,
		AuthorizationIssue:   true,
		AdministrativeIssue:  false,
		ReturnWindow:         ReturnWindow60CalendarDays,
		ThresholdCategory:    ThresholdUnauthorized05Percent,
		BaseSeverity:         95.0,
		TaxonomyVersion:      TaxonomyVersion,
		OperationalGuidance:  GuidanceAuthorizationReviewRequired,
		GuidanceSummary:      "Route for authorization review; the risk engine and AI assessment do not determine authorization validity or release disposition.",
		SourceProvenance:     publicSources(unauthorizedReasonSource),
	},
	"R11": {
		Code:                 "R11",
		ShortLabel:           "ENTRY_NOT_IN_ACCORDANCE_WITH_AUTHORIZATION",
		Title:                "Customer Advises Entry is Not in Accordance with the Terms of the Authorization",
		Description:          "The Receiver advises that an authorization exists, but the entry is not in accordance with the terms of that authorization.",
		NormalizedCategory:   CategoryAuthorizationTerms,
		OperationalSeverity:  SeverityCritical,
		RetryCharacteristic:  NonRetryable,
		AccountDataIssue:     false,
		AuthorizationIssue:   true,
		AdministrativeIssue:  false,
		ReturnWindow:         ReturnWindow60CalendarDays,
		ThresholdCategory:    ThresholdUnauthorized05Percent,
		BaseSeverity:         85.0,
		TaxonomyVersion:      TaxonomyVersion,
		OperationalGuidance:  GuidanceAuthorizationReviewRequired,
		GuidanceSummary:      "Review the entry against the represented authorization terms and do not automatically reinitiate from risk output alone.",
		SourceProvenance:     publicSources(unauthorizedReasonSource),
	},
	"R16": {
		Code:                 "R16",
		ShortLabel:           "ACCOUNT_FROZEN_OR_RETURNED_PER_OFAC_INSTRUCTION",
		Title:                "Account Frozen / Entry Returned Per OFAC Instruction",
		Description:          "Current public Nacha materials describe R16 for an account frozen by the RDFI or an entry returned per OFAC instruction; a separate R90 sanctions-screening code is scheduled for a future effective date.",
		NormalizedCategory:   CategoryOFACRestricted,
		OperationalSeverity:  SeverityCritical,
		RetryCharacteristic:  NonRetryable,
		AccountDataIssue:     false,
		AuthorizationIssue:   false,
		AdministrativeIssue:  false,
		ReturnWindow:         ReturnWindow2BankingDays,
		ThresholdCategory:    ThresholdRegulatoryRestricted,
		BaseSeverity:         85.0,
		TaxonomyVersion:      TaxonomyVersion,
		OperationalGuidance:  GuidanceComplianceReviewRequired,
		GuidanceSummary:      "Route for compliance review. No percentage threshold is invented for this category, and SentinelFlow does not make a sanctions or legal adjudication.",
		SourceProvenance:     publicSources(r16TransitionSource),
	},
	"R20": {
		Code:                 "R20",
		ShortLabel:           "NON_TRANSACTION_ACCOUNT",
		Title:                "Non-Transaction Account",
		Description:          "The entry was returned because the receiving account is not eligible for the transaction type.",
		NormalizedCategory:   CategoryAccountStatus,
		OperationalSeverity:  SeverityHigh,
		RetryCharacteristic:  RetryableWithCorrection,
		AccountDataIssue:     true,
		AuthorizationIssue:   false,
		AdministrativeIssue:  true,
		ReturnWindow:         ReturnWindow2BankingDays,
		ThresholdCategory:    ThresholdOverall15Percent,
		BaseSeverity:         50.0,
		TaxonomyVersion:      TaxonomyVersion,
		OperationalGuidance:  GuidanceCorrectionRequired,
		GuidanceSummary:      "Review account eligibility and obtain corrected payment instructions before a subsequent entry.",
		SourceProvenance:     publicSources(),
	},
	"R29": {
		Code:                 "R29",
		ShortLabel:           "CORPORATE_CUSTOMER_ADVISES_NOT_AUTHORIZED",
		Title:                "Corporate Customer Advises Not Authorized",
		Description:          "The corporate Receiver advises that the debit entry was not authorized.",
		NormalizedCategory:   CategoryUnauthorized,
		OperationalSeverity:  SeverityCritical,
		RetryCharacteristic:  NonRetryable,
		AccountDataIssue:     false,
		AuthorizationIssue:   true,
		AdministrativeIssue:  false,
		ReturnWindow:         ReturnWindow2BankingDays,
		ThresholdCategory:    ThresholdUnauthorized05Percent,
		BaseSeverity:         90.0,
		TaxonomyVersion:      TaxonomyVersion,
		OperationalGuidance:  GuidanceAuthorizationReviewRequired,
		GuidanceSummary:      "Route for authorization review and do not automatically reinitiate or release based on risk output.",
		SourceProvenance:     publicSources(unauthorizedReasonSource),
	},
}

// LookupReturnCode resolves an ACH return code from the representative MVP taxonomy catalog.
func LookupReturnCode(code string) (ACHReturnCode, error) {
	upper := strings.ToUpper(strings.TrimSpace(code))
	if def, ok := Catalog[upper]; ok {
		return def, nil
	}
	return ACHReturnCode{}, fmt.Errorf("%w: %q", ErrInvalidReturnCode, code)
}
