package returnrisk

import (
	"fmt"
	"strings"
)

// TaxonomyVersion defines the active ACH return code regulatory schema version.
const TaxonomyVersion = "ACH-RETURN-TAXONOMY-V1"

// Catalog holds the representative MVP set of ACH return code definitions.
var Catalog = map[string]ACHReturnCode{
	"R01": {
		Code:                "R01",
		ShortLabel:          "INSUFFICIENT_FUNDS",
		Title:               "Insufficient Funds",
		Description:         "Available balance is not sufficient to cover the dollar value of the debit entry.",
		NormalizedCategory:  CategoryInsufficientFunds,
		OperationalSeverity: SeverityMedium,
		RetryCharacteristic: RetryableOnce,
		AccountDataIssue:    false,
		AuthorizationIssue:  false,
		AdministrativeIssue: false,
		ReturnWindow:        ReturnWindow2BankingDays,
		ThresholdCategory:   ThresholdOverall15Percent,
		BaseSeverity:        45.0,
		SourceReference:     "Nacha Operating Rules & Guidelines / FedACH Operations",
		TaxonomyVersion:     TaxonomyVersion,
		RegulatoryCitations: []string{
			"Nacha Operating Rules Subsection 2.12 (Reinitiation of Returned Entries)",
			"Federal Reserve Operating Circular No. 4 (FedACH)",
		},
		RemediationDirective: "Eligible for reinitiation up to 2 times within 180 days of original settlement date. Queue for scheduled liquidity retry.",
	},
	"R02": {
		Code:                "R02",
		ShortLabel:          "ACCOUNT_CLOSED",
		Title:               "Account Closed",
		Description:         "A previously active transaction account has been closed by action of the customer or RDFI.",
		NormalizedCategory:  CategoryAccountStatus,
		OperationalSeverity: SeverityHigh,
		RetryCharacteristic: NonRetryable,
		AccountDataIssue:    true,
		AuthorizationIssue:  false,
		AdministrativeIssue: true,
		ReturnWindow:        ReturnWindow2BankingDays,
		ThresholdCategory:   ThresholdAdministrative3Percent,
		BaseSeverity:        50.0,
		SourceReference:     "Nacha Operating Rules & Guidelines / FedACH Operations",
		TaxonomyVersion:     TaxonomyVersion,
		RegulatoryCitations: []string{
			"Nacha Operating Rules Section 3.2 (RDFI Return Obligations)",
			"FFIEC Retail Payment Systems Handbook - Administrative Returns",
		},
		RemediationDirective: "Halt recurring debits immediately. Prompt customer for replacement payment method and verified account credentials.",
	},
	"R03": {
		Code:                "R03",
		ShortLabel:          "NO_ACCOUNT_UNABLE_TO_LOCATE",
		Title:               "No Account / Unable to Locate Account",
		Description:         "The account number directed to the RDFI does not correspond to an existing open account, or does not match customer records.",
		NormalizedCategory:  CategoryAccountData,
		OperationalSeverity: SeverityHigh,
		RetryCharacteristic: RetryableWithCorrection,
		AccountDataIssue:    true,
		AuthorizationIssue:  false,
		AdministrativeIssue: true,
		ReturnWindow:        ReturnWindow2BankingDays,
		ThresholdCategory:   ThresholdAdministrative3Percent,
		BaseSeverity:        55.0,
		SourceReference:     "Nacha Operating Rules & Guidelines / FedACH Operations",
		TaxonomyVersion:     TaxonomyVersion,
		RegulatoryCitations: []string{
			"Nacha Operating Rules Subsection 2.12.4 & Section 3.2",
			"Nacha Administrative Return Rate Monitoring Framework",
		},
		RemediationDirective: "Do not reinitiate with identical data. Require customer to update and verify routing/account number pairing.",
	},
	"R04": {
		Code:                "R04",
		ShortLabel:          "INVALID_ACCOUNT_STRUCTURE",
		Title:               "Invalid Account Number Structure",
		Description:         "The account number field does not conform to the account structure guidelines of the RDFI (invalid length or check digit).",
		NormalizedCategory:  CategoryAccountData,
		OperationalSeverity: SeverityHigh,
		RetryCharacteristic: RetryableWithCorrection,
		AccountDataIssue:    true,
		AuthorizationIssue:  false,
		AdministrativeIssue: true,
		ReturnWindow:        ReturnWindow2BankingDays,
		ThresholdCategory:   ThresholdAdministrative3Percent,
		BaseSeverity:        55.0,
		SourceReference:     "Nacha Operating Rules & Guidelines / FedACH Operations",
		TaxonomyVersion:     TaxonomyVersion,
		RegulatoryCitations: []string{
			"Nacha Operating Rules Subsection 2.12.4 & Appendix 4",
			"Federal Reserve FedACH Operations Guide",
		},
		RemediationDirective: "Perform pre-flight account format validation. Obtain corrected account structure before re-originating.",
	},
	"R05": {
		Code:                "R05",
		ShortLabel:          "UNAUTHORIZED_CONSUMER_CORPORATE_SEC",
		Title:               "Unauthorized Debit to Consumer Account Using Corporate SEC Code",
		Description:         "A debit entry was transmitted to a consumer account using a corporate Standard Entry Class code (CCD, CTX) without consumer authorization.",
		NormalizedCategory:  CategoryUnauthorized,
		OperationalSeverity: SeverityCritical,
		RetryCharacteristic: NonRetryable,
		AccountDataIssue:    false,
		AuthorizationIssue:  true,
		AdministrativeIssue: false,
		ReturnWindow:        ReturnWindow60CalendarDays,
		ThresholdCategory:   ThresholdUnauthorized05Percent,
		BaseSeverity:        90.0,
		SourceReference:     "Nacha Operating Rules & Guidelines / 12 CFR Part 1005 (Regulation E)",
		TaxonomyVersion:     TaxonomyVersion,
		RegulatoryCitations: []string{
			"12 CFR Part 1005 (Regulation E - Electronic Fund Transfers)",
			"Nacha Operating Rules Article Three (Unauthorized Consumer Debits)",
		},
		RemediationDirective: "Quarantine feed. Re-originating under corporate SEC code is prohibited. Requires valid consumer authorization and proper SEC code (e.g. PPD/WEB).",
	},
	"R07": {
		Code:                "R07",
		ShortLabel:          "AUTHORIZATION_REVOKED",
		Title:               "Authorization Revoked by Customer",
		Description:         "The consumer customer who previously authorized the debit has formally revoked authorization with the Originator or RDFI.",
		NormalizedCategory:  CategoryUnauthorized,
		OperationalSeverity: SeverityCritical,
		RetryCharacteristic: Prohibited,
		AccountDataIssue:    false,
		AuthorizationIssue:  true,
		AdministrativeIssue: false,
		ReturnWindow:        ReturnWindow60CalendarDays,
		ThresholdCategory:   ThresholdUnauthorized05Percent,
		BaseSeverity:        85.0,
		SourceReference:     "Nacha Operating Rules & Guidelines / 12 CFR § 1005.10(c)",
		TaxonomyVersion:     TaxonomyVersion,
		RegulatoryCitations: []string{
			"12 CFR § 1005.10(c) (Consumer Revocation of Preauthorized Transfers)",
			"Nacha Operating Rules Section 2.3 & Section 3.12",
		},
		RemediationDirective: "Revocation is permanent for the authorization mandate. Reinitiation is illegal without executing a fresh written/electronic authorization.",
	},
	"R08": {
		Code:                "R08",
		ShortLabel:          "PAYMENT_STOPPED",
		Title:               "Payment Stopped",
		Description:         "The Receiver has placed a stop payment order with the RDFI for this specific debit entry or payment series.",
		NormalizedCategory:  CategoryAdministrative,
		OperationalSeverity: SeverityHigh,
		RetryCharacteristic: NonRetryable,
		AccountDataIssue:    false,
		AuthorizationIssue:  true,
		AdministrativeIssue: false,
		ReturnWindow:        ReturnWindow2BankingDays,
		ThresholdCategory:   ThresholdOverall15Percent,
		BaseSeverity:        60.0,
		SourceReference:     "Nacha Operating Rules & Guidelines / 12 CFR § 1005.10(c)",
		TaxonomyVersion:     TaxonomyVersion,
		RegulatoryCitations: []string{
			"12 CFR § 1005.10(c) (Stop Payment Rights)",
			"Nacha Operating Rules Section 3.8 (Stop Payment Orders)",
			"Uniform Commercial Code UCC § 4-403",
		},
		RemediationDirective: "Do not re-originate entry. Contact customer to resolve underlying commercial dispute and release stop payment.",
	},
	"R10": {
		Code:                "R10",
		ShortLabel:          "CUSTOMER_ADVISES_UNAUTHORIZED",
		Title:               "Customer Advises Unauthorized / Notice Not Provided",
		Description:         "The Receiver has executed a Written Statement of Unauthorized Debit (WSUD) advising that the entry was unauthorized or improper.",
		NormalizedCategory:  CategoryUnauthorized,
		OperationalSeverity: SeverityCritical,
		RetryCharacteristic: Prohibited,
		AccountDataIssue:    false,
		AuthorizationIssue:  true,
		AdministrativeIssue: false,
		ReturnWindow:        ReturnWindow60CalendarDays,
		ThresholdCategory:   ThresholdUnauthorized05Percent,
		BaseSeverity:        95.0,
		SourceReference:     "Nacha Operating Rules & Guidelines / 12 CFR § 1005.11 (Reg E)",
		TaxonomyVersion:     TaxonomyVersion,
		RegulatoryCitations: []string{
			"12 CFR § 1005.11 (Regulation E Error Resolution Procedures)",
			"Nacha Operating Rules Article Three (WSUD Requirements)",
			"OCC Bulletin 2006-39 (ACH Risk Management Guidance)",
		},
		RemediationDirective: "Immediate escalation to Compliance. Quarantine counterparty. Counts toward 0.5% threshold. Fresh proof of authorization mandatory.",
	},
	"R16": {
		Code:                "R16",
		ShortLabel:          "ACCOUNT_FROZEN_OR_OFAC",
		Title:               "Account Frozen / Entry Prohibited by OFAC",
		Description:         "Access to account is blocked by RDFI due to legal action/levy or the entry is prohibited under Office of Foreign Assets Control (OFAC) sanctions.",
		NormalizedCategory:  CategoryOFACRestricted,
		OperationalSeverity: SeverityCritical,
		RetryCharacteristic: Prohibited,
		AccountDataIssue:    false,
		AuthorizationIssue:  false,
		AdministrativeIssue: false,
		ReturnWindow:        ReturnWindow2BankingDays,
		ThresholdCategory:   ThresholdRegulatoryRestricted,
		BaseSeverity:        85.0,
		SourceReference:     "31 CFR Part 500 et seq. (OFAC) / Nacha Operating Rules Section 3.2",
		TaxonomyVersion:     TaxonomyVersion,
		RegulatoryCitations: []string{
			"31 CFR Chapter V (Office of Foreign Assets Control Sanctions Regulations)",
			"Nacha Operating Rules Section 3.2.2 (OFAC Compliance Obligations)",
			"Bank Secrecy Act / USA PATRIOT Act",
		},
		RemediationDirective: "Cease all transaction activity immediately. Flag transaction for BSA/AML Officer and Legal review. Reinitiation strictly prohibited by federal law.",
	},
	"R20": {
		Code:                "R20",
		ShortLabel:          "NON_TRANSACTION_ACCOUNT",
		Title:               "Non-Transaction Account",
		Description:         "The ACH entry is destined for a non-transaction account prohibited from accepting ACH debits/credits under banking policy or Regulation D.",
		NormalizedCategory:  CategoryAccountStatus,
		OperationalSeverity: SeverityHigh,
		RetryCharacteristic: RetryableWithCorrection,
		AccountDataIssue:    true,
		AuthorizationIssue:  false,
		AdministrativeIssue: true,
		ReturnWindow:        ReturnWindow2BankingDays,
		ThresholdCategory:   ThresholdOverall15Percent,
		BaseSeverity:        50.0,
		SourceReference:     "12 CFR Part 204 (Regulation D) / Nacha Operating Rules Section 3.2",
		TaxonomyVersion:     TaxonomyVersion,
		RegulatoryCitations: []string{
			"12 CFR Part 204 (Regulation D - Reserve Requirements)",
			"Nacha Operating Rules Section 3.2 (RDFI Account Eligibility)",
		},
		RemediationDirective: "Instruct customer to supply an eligible Demand Deposit Account (DDA) checking or valid unrestricted transaction account.",
	},
	"R29": {
		Code:                "R29",
		ShortLabel:          "CORPORATE_CUSTOMER_NOT_AUTHORIZED",
		Title:               "Corporate Customer Advises Not Authorized",
		Description:         "Corporate Receiver (non-consumer) has advised the RDFI that the debit entry was not authorized under corporate trading partner agreement.",
		NormalizedCategory:  CategoryUnauthorized,
		OperationalSeverity: SeverityCritical,
		RetryCharacteristic: Prohibited,
		AccountDataIssue:    false,
		AuthorizationIssue:  true,
		AdministrativeIssue: false,
		ReturnWindow:        ReturnWindow2BankingDays,
		ThresholdCategory:   ThresholdUnauthorized05Percent,
		BaseSeverity:        90.0,
		SourceReference:     "Nacha Operating Rules Article Three / UCC Article 4A-202",
		TaxonomyVersion:     TaxonomyVersion,
		RegulatoryCitations: []string{
			"Uniform Commercial Code UCC Article 4A-202 (Authorized and Verified Funds Transfers)",
			"Nacha Operating Rules Section 3.12 (Corporate Unauthorized Return Rules)",
		},
		RemediationDirective: "Quarantine corporate debit feed. Counts toward 0.5% Unauthorized Return Rate. Re-execute corporate authorization before attempting settlement.",
	},
}

// LookupReturnCode resolves an ACH return code from the taxonomy catalog.
func LookupReturnCode(code string) (ACHReturnCode, error) {
	upper := strings.ToUpper(strings.TrimSpace(code))
	if def, ok := Catalog[upper]; ok {
		return def, nil
	}
	return ACHReturnCode{}, fmt.Errorf("%w: %q", ErrInvalidReturnCode, code)
}
