"""RemediationAgent — Governed Sandbox Remediation Specialist (SGACA Phase P07).

Formal Invariant: AgentProposal != CandidateMutationAuthority.
The RemediationAgent (Autonomy Level A2: Sandbox Candidate Creation) proposes
allowlisted, structured remediation intents. Authoritative candidate bytes and
numerical totals are strictly computed and generated by the Go Control Plane.
"""

from __future__ import annotations

import hashlib
import json
import logging
from typing import Any, Dict, List, Union

import google.adk.agents as adk_agents
import google.adk.runners as adk_runners
from contracts.manifests import FIXED_AGENT_ROSTER
from contracts.orchestration import AgentHandoffEnvelope
from contracts.remediation import (
    RemediationOperation,
    RemediationOperationType,
    RemediationPlan,
)
from guardrails.boundary import GuardedModelBoundary
from guardrails.evidence import (
    AuthorizedEvidenceSet,
)
from models.envelope import AgentContextEnvelope

logger = logging.getLogger("sentinel.ai.remediation")


class RemediationAgent:
    """Governed Sandbox Remediation Planning Specialist."""

    def __init__(
        self,
        model_name: str = "gemini-3.5-flash",
        gateway_base_url: str = "http://localhost:8080",
    ):
        self.manifest = FIXED_AGENT_ROSTER["RemediationAgent"]
        self.model_name = model_name
        self.gateway_base_url = gateway_base_url
        self.boundary = GuardedModelBoundary(default_model=self.model_name)

        # Real Google ADK Agent & Runner Runtime Objects
        self.adk_agent = adk_agents.Agent(
            name=self.manifest.name,
            model=self.model_name,
            instruction=(
                "You are the SentinelFlow Remediation Agent.\n"
                "Your role is to propose allowlisted, structured remediation intents for quarantined financial files.\n"
                "CRITICAL NON-NEGOTIABLE SAFETY CONSTRAINTS:\n"
                "1. Autonomy Level A2: You propose remediation intents; the Go Control Plane computes authoritative totals and candidate bytes.\n"
                "2. Immutable Originals: You never mutate original files or propose patches against previous candidates.\n"
                "3. Allowlisted Operations ONLY: 'RECOMPUTE_BATCH_CONTROL_TOTAL', 'RECOMPUTE_FILE_CONTROL_TOTAL'.\n"
                "4. You have zero authority to approve, release, or mutate financial data directly.\n"
                "5. All citations must strictly reference provided authorized evidence IDs."
            ),
            output_key="remediation_plan",
        )
        self.adk_runner = adk_runners.InMemoryRunner(agent=self.adk_agent)

    def run(
        self,
        envelope_data: Union[Dict[str, Any], AgentContextEnvelope, AgentHandoffEnvelope],
        attempt_number: int = 1,
    ) -> RemediationPlan:
        """Executes evidence-grounded remediation proposal generation."""
        if isinstance(envelope_data, dict):
            tenant_id = str(envelope_data.get("tenant_id", "default"))
            workflow_id = str(envelope_data.get("workflow_id", "wf-unknown"))
            incident_id = int(envelope_data.get("incident_id", 0))
            artifact_id = int(envelope_data.get("artifact_id", 0))
            artifact_sha = str(envelope_data.get("artifact_sha256", ""))
            evidence_refs = list(envelope_data.get("authorized_evidence_refs", []))
            findings = list(envelope_data.get("findings", []))
            envelope = AgentContextEnvelope(
                tenant_id=tenant_id,
                workflow_id=workflow_id,
                incident_id=incident_id,
                artifact_id=artifact_id,
                artifact_sha256=artifact_sha,
                authorized_evidence_refs=evidence_refs,
                findings=findings,
            )
        elif isinstance(envelope_data, AgentHandoffEnvelope):
            tenant_id = envelope_data.tenant_id
            workflow_id = envelope_data.workflow_id
            incident_id = envelope_data.incident_id
            artifact_id = envelope_data.artifact_id
            artifact_sha = envelope_data.artifact_sha256
            evidence_refs = list(envelope_data.authorized_evidence_refs)
            findings = []
            envelope = AgentContextEnvelope(
                tenant_id=tenant_id,
                workflow_id=workflow_id,
                incident_id=incident_id,
                artifact_id=artifact_id,
                artifact_sha256=artifact_sha,
                authorized_evidence_refs=evidence_refs,
                findings=[],
            )
        else:
            envelope = envelope_data
            tenant_id = envelope.tenant_id
            workflow_id = envelope.workflow_id or "wf-unknown"
            incident_id = envelope.incident_id
            artifact_id = envelope.artifact_id
            artifact_sha = envelope.artifact_sha256
            evidence_refs = list(envelope.authorized_evidence_refs)
            findings = list(envelope.findings)

        # Setup Evidence Grounding
        evidence_set = AuthorizedEvidenceSet(initial_refs=set(evidence_refs))

        # Define deterministic fallback callback
        def _fallback(
            env: AgentContextEnvelope, auth_set: AuthorizedEvidenceSet
        ) -> RemediationPlan:
            return self._deterministic_fallback(
                tenant_id=tenant_id,
                workflow_id=workflow_id,
                incident_id=incident_id,
                artifact_id=artifact_id,
                artifact_sha=artifact_sha,
                attempt_number=attempt_number,
                findings=findings,
                evidence_refs=evidence_refs,
            )

        role_prompt = (
            "ROLE SPECIFIC INSTRUCTION (RemediationAgent):\n"
            "Propose allowlisted remediation operations (RECOMPUTE_BATCH_CONTROL_TOTAL, RECOMPUTE_FILE_CONTROL_TOTAL) "
            "to address the validation findings in the quarantined parent artifact.\n"
            "You must cite authorized evidence references. Do not attempt to calculate raw totals yourself."
        )

        result = self.boundary.invoke(
            envelope=envelope,
            response_schema=RemediationPlan,
            role_system_prompt=role_prompt,
            evidence_set=evidence_set,
            fallback_fn=_fallback,
            strict_grounding=True,
        )

        if result.success and result.output:
            plan = result.output
            plan.workflow_id = workflow_id
            plan.tenant_id = tenant_id
            plan.incident_id = incident_id
            plan.artifact_id = artifact_id
            plan.expected_parent_sha256 = artifact_sha
            plan.attempt_number = attempt_number
            if not plan.plan_hash:
                plan_payload = f"{workflow_id}:{attempt_number}:{artifact_sha}:{json.dumps([op.model_dump() for op in plan.operations])}"
                plan.plan_hash = hashlib.sha256(plan_payload.encode("utf-8")).hexdigest()
            return plan

        # Return fallback on failure
        return self._deterministic_fallback(
            tenant_id,
            workflow_id,
            incident_id,
            artifact_id,
            artifact_sha,
            attempt_number,
            findings,
            evidence_refs,
        )

    def _deterministic_fallback(
        self,
        tenant_id: str,
        workflow_id: str,
        incident_id: int,
        artifact_id: int,
        artifact_sha: str,
        attempt_number: int,
        findings: List[Any],
        evidence_refs: List[str],
    ) -> RemediationPlan:
        """Deterministic rule-grounded fallback for remediation proposal generation."""
        ops = [
            RemediationOperation(
                operation_type=RemediationOperationType.RECOMPUTE_BATCH_CONTROL_TOTAL,
                target_ref="BATCH-1",
                finding_refs=evidence_refs,
                rationale="Recompute batch debit, credit, entry count, and entry hash totals from parsed entry records",
                evidence_refs=evidence_refs,
            ),
            RemediationOperation(
                operation_type=RemediationOperationType.RECOMPUTE_FILE_CONTROL_TOTAL,
                target_ref="FILE_CONTROL",
                finding_refs=evidence_refs,
                rationale="Recompute file-level batch count, block count, entry count, debits, credits, and entry hash sum",
                evidence_refs=evidence_refs,
            ),
        ]

        plan_payload = f"{workflow_id}:{attempt_number}:{artifact_sha}:deterministic"
        plan_hash = hashlib.sha256(plan_payload.encode("utf-8")).hexdigest()

        return RemediationPlan(
            schema_version="1.0",
            workflow_id=workflow_id,
            tenant_id=tenant_id,
            incident_id=incident_id,
            artifact_id=artifact_id,
            expected_parent_sha256=artifact_sha,
            attempt_number=attempt_number,
            plan_hash=plan_hash,
            operations=ops,
            finding_refs=evidence_refs,
            unresolved_findings=[],
            confidence="HIGH",
            requires_human_attention=False,
            evidence_refs=evidence_refs,
        )
